LED	EQU	P2.0		; NAMING LED PIN

	ORG	000H		; STARTING ADDRESS
MAIN: 				; MAIN FUNCTION
	MOV	P0,#00000001B
	MOV	P1,#00H
	MOV	P2,#00H
	MOV	P3,#00000100B
	SETB	LED

READSW: 
	MOV	A,P0    	;  MOVING PORT VALUE TO ACCU.
	RRC	A		;  GETTING THE INPUT BIT TO CARRY
	JC	NXT		;  IF SWITCH ON JUMP TO NXT
	CLR	LED		;  TURN OFF LED BECAUSE SW IS OFF
	SJMP	READSW  	;  READ SWITCH STATUS AGAIN.
NXT:	
	SETB	LED
	SJMP	READSW  	;  JUMPING TO READSW 
	
	END			; END OF PROGRAM